version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: pacientes
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: